### ISSUE TITLE
function in the loop not generating custom sizes for all images

### ISSUE THREAD

**Issue by TheeBryanWhite** [franz-josef-kaiser/Dynamic-Image-Resize#11]
I love this plugin! It's been working great for a while but I think I found a bug. I ran the function inside a loop that returns blog posts. Each one has a featured image. So I get the thumbnail URL before I run the resize function and give the var to the function. But when it loads the page, it only generates thumbnails for the first post and the last post. There are 4 on the page. So the middle two thumbnails are either the original size or a random, previously generated image size.

**Comment by franz-josef-kaiser** [comment]
@TheeBryanWhite Why did you close the issue? Also, please show your loop. Maybe there's the bug in there.
